### ISSUE TITLE
Idea: Caching Index and Read

### ISSUE THREAD

**Issue by Nizari** [cloudcreativity/demo-laravel-json-api#22]
He Chris, maybe for after release of version 1. To be able to cache the get calls for performance. To be able to do this with filecaching would be great as well. For this I used http://www.php-cache.com/en/latest/. They have lots of drivers, sadly no laravel yet.

I also created some tests to validate that filecaching works with *tagging*. https://gist.github.com/Nizari/deaeab8a17c82b545e7e79d947d55302

The general idea would be to use your resources combined with the possible includes, to label each caching item with the corresponding tags. For example: Lets say you have a resource *Users* with possible includes of *Orders* & *Invoices*. You would tag the `/users` (or any variation like `/users?include=orders`) with the the tags `users,orders,invoices`. This way, whenever you change any of those 3 resources, it should automatically invalidate the tag of this resource.

This way, if you update order data, it will recognise that the `/users` call is probably also invalid and will be recached.

Looking forward to your opinion regarding how and if this is possible.
Keep up the good work.

**Comment by lindyhopchris** [comment]
Hi @Nizari 

Sorry replying to this has taken a long time. Yes it would be good to add caching at some point, but definitely after the `1.0.0` release. This would be a huge bit of work though that would require working through all the different points at which the cache needs to be invalidated. Developers would also need to hook into invalidating the cache when records change outside of JSON API... e.g. if I save changes to a model in a queued job, I'd need to know to clear the JSON API cache for that - but only if an attribute has changed that I'm including in my JSON API resource for that model.

In terms of drivers, I would prefer to use the Laravel cache as the default, but you could potentially use any other driver as long as your wrap it in the Illuminate Cache contract.

I'm going to close this issue here and re-open it in the `cloudcreativity/laravel-json-api` repo as that's where it should be.
