### ISSUE TITLE
Authentication flow with JWT?

### ISSUE THREAD

**Issue by GIANTCRAB** [cloudcreativity/demo-laravel-json-api#7]
Thanks for the repo! I've been reading through the code and JSON API spec.

There's some discussions on the JSON API forum about authentication - http://discuss.jsonapi.org/t/example-json-api-for-accounts/234/11

I'm wondering if there's a way which we could craft an authentication flow for JWT or OAuth and put it in the demo app too? 

Thanks.

**Comment by lindyhopchris** [comment]
Hi.

Yes, I need to add in a demo of this flow. In my applications I use the following for auth:
https://github.com/tymondesigns/jwt-auth

I don't wrap it in JSON API though - I just have a small integration to ensure that any failures to authenticate with a token send JSON API errors.

It would be great to drop it into the demo app... I'll see when I have time: at the moment any time I do have is being spent on the v1.0 things I'm trying to get through on the `laravel-json-api` package.

**Comment by GIANTCRAB** [comment]
So to login, the client would make a POST request to /api/v1/tokens with:

```
"data": {
    "attributes": {
        "email": "abc@lol.com",
        "password": "lol"
    }
}
```
And then the controller is a non-eloquent one that only allows POST requests? How should validation be done?

I could make a PR to this repo once I got the flow right.

**Comment by lindyhopchris** [comment]
You can do it like that if you wanted. I've got to admit I don't - because frontend libraries don't expect it like that. E.g. I use this on the frontend:
https://github.com/jpadilla/ember-simple-auth-token

Which doesn't make the request as a JSON API request.

However, the way you're proposing to do it would make sense as a JSON API work-flow, so would be good for the demo app to have it that way. If we get it working, we could potentially create a package for it so people can install it in their Laravel applications if they want to use JWT?

**Comment by lindyhopchris** [comment]
No, was planning on using the user class when auth was added in. So use the `User` class for the auth.

**Comment by GIANTCRAB** [comment]
I'm kind of facing some issues whilst writing up the controller, etc. Would appreciate some insights into these issues. 

Unsure how to throw an error for incorrect login details: https://github.com/GIANTCRAB/demo-laravel-json-api/issues/1 (I'll also do a PR for this in the docs lol)

Exception when attempting to do a DELETE (logout): https://github.com/GIANTCRAB/demo-laravel-json-api/issues/2 (This one I really can't figure out, might take some time to debug?)

**Comment by lindyhopchris** [comment]
The delete one I believe is an issue that has been fixed on the `develop` branch of `laravel-json-api` and will be included in the 0.10 release that I'll be doing shortly. 

I'm not sure what the point is of the delete unless you're going to do something via the JWT library? There's no point logging out the user as the user is only logged in because they've sent their JWT token (as this is stateless from the server's perspective, there's nothing to log out as the user isn't logged in unless they send a token).

In terms of returning an error response for the incorrect login details, what you're doing is fine. There's no need to throw anything if your using the `$this->reply()->errors()`.

**Comment by GIANTCRAB** [comment]
> The delete one I believe is an issue that has been fixed on the develop branch of laravel-json-api and will be included in the 0.10 release that I'll be doing shortly.

Alright, looking forward to the release! I'll definitely try my best
to help out with docs. :)

> I'm not sure what the point is of the delete unless you're going to do something via the JWT library? There's no point logging out the user as the user is only logged in because they've sent their JWT token (as this is stateless from the server's perspective, there's nothing to log out as the user isn't logged in unless they send a token).

The DELETE/logout is to allow the token to become
blacklisted/invalidated and thus, user would no longer be able to use
the same token.

> In terms of returning an error response for the incorrect login details, what you're doing is fine. There's no need to throw anything if your using the $this->reply()->errors().

Alright, thanks. But is there any particular response format for the
error? Should I just use the format extracted from the JSON API spec?

Thanks again!

**Comment by lindyhopchris** [comment]
Yes you should use a JSON API error. Can you just mark it with a `@todo` comment? There's ways to do it already in the package, but they're undocumented. So probably better I look into that as I can't remember it off the top of my head. What you've done for the moment will be fine for now as the client will at least get the correct HTTP status.

Delete stuff sounds good - good to hear the JWT package will blacklist it.

**Comment by lindyhopchris** [comment]
Closing this because it is a bit out-of-date.
